### ISSUE TITLE
更新到 1.0.1 版本后，发现断点都乱了呢

### ISSUE THREAD

**Issue by slightun** [colinsusie/skynetda#13]
参考描述把 skynet 源码、skynetda 升级到了最新。

**发现调试有两个问题：**
1. F10 单步执行遇到全局函数时，会直接进入全局函数，继续单步后，断点就乱了
如下：log_info 是个全局工具函数
![image](https://user-images.githubusercontent.com/10279336/117779961-bef97480-b271-11eb-9d4c-3bb6661cfd21.png)
![image](https://user-images.githubusercontent.com/10279336/117779929-b86afd00-b271-11eb-94fb-9cf00ec38a15.png)

2. 感觉第一个问题会导致全局函数之后的代码无法断点。

之前版本的 skynetda 是正常的。

**Comment by colinsusie** [comment]
我看一下是什么问题

**Comment by colinsusie** [comment]
请问你的skynet debugger升到 1.0.1了吗，在我自己的环境下(Windows WSL)测试没有发现问题：插件版本如图所示：
![4](https://user-images.githubusercontent.com/11472347/117782799-8dce7380-b274-11eb-95dd-41db605fd12a.jpg)

下面是单步到log_info函数：
![1](https://user-images.githubusercontent.com/11472347/117782956-b0f92300-b274-11eb-8d87-a1efedeadbde.jpg)

按F10跳过了：
![2](https://user-images.githubusercontent.com/11472347/117783027-c1a99900-b274-11eb-8395-61723745cb5d.jpg)

我再重新跑，然后按F11，成功进入了log_info，里面也可以单步：
![3](https://user-images.githubusercontent.com/11472347/117783134-d7b75980-b274-11eb-8983-bb0c27cfce28.jpg)

要不要再看看是不是哪里没有更新？一时想不出问题在哪里，

另外，可以把你的launch.json贴出来看一下吗？

**Comment by slightun** [comment]
好的。我再检查一下是不是哪里更新错了。
【版本、skynet 源码我有对比过，skynet执行文件也重新生成过】

Launch.json 的话没特别的：
![image](https://user-images.githubusercontent.com/10279336/117789331-cf621d00-b27a-11eb-9001-2f505290822d.png)

所有代码我放在了 demo 目录下，包括 config 文件

**Comment by colinsusie** [comment]
你把skynet编译成 demoserver吗？还是demoserver只是一个目录？

你可否把整个工程打成一个包发给我看看，或者弄一个可以重现的Demo给我看也行。

**Comment by slightun** [comment]
谢谢~~ 是加个 qq 好友么？ 623854412
我整理个可重现的 demo

**Comment by colinsusie** [comment]
好的。

**Comment by slightun** [comment]
**感谢大佬帮解决。原因是重新编译 skynet 的操作有误。
正确操作：**
make clean
cd 3rd/lua
make clean
cd ../..
make linux
