### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by NormalLee** [colinsusie/skynetda#14]
[:00000001] start debug: 	vscdebuglog
vscdebug.lua:445
[:00000002] init service failed: ./lualib/skynet.lua:605: call to invalid address .service
stack traceback:
	[C]: in function 'error'
	./lualib/skynet.lua:605: in function 'skynet.call'
	./lualib/skynet.lua:869: in function 'skynet.uniqueservice'
	./lualib/skynet/vscdebug.lua:383: in local 'f'
	./lualib/skynet/require.lua:103: in function 'skynet.require.init_all'
	./lualib/skynet.lua:934: in function <./lualib/skynet.lua:933>
	[C]: in function 'xpcall'
	./lualib/skynet.lua:937: in function 'skynet.init_service'
	./lualib/skynet.lua:950: in upvalue 'f'
	./lualib/skynet.lua:253: in function <./lualib/skynet.lua:252>
skynet.lua:939
[:00000002] KILL self

**Comment by colinsusie** [comment]
你是怎么执行的？把执行命令，或launch.json贴一下？

**Comment by NormalLee** [comment]
launch.json是这个
"version": "0.2.0",
    "configurations": [
        {
            "name": "skynet debugger",
            "type": "lua",
            "request": "launch",
            "workdir": "${workspaceFolder}",
            "program": "./skynet",
            "config": "./examples/config_vsc",
            "service": "./service"
        }
    ]

**Comment by NormalLee** [comment]
用的版本是1.0.1的这个调试器

**Comment by colinsusie** [comment]
我按照这个过程：

- 下载编译skynet
```sh
git clone https://github.com/colinsusie/skynet.git skynet2
cd skynet2/
make linux
```
- vscode 远程打开WSL里的skynet2工程
- 在VSCode里点 create a launch.json file
- 打开 testvscdebug.lua 文件，在里面下断点
- 按F5，能够正常断点

你看看哪里有不一样的地方吗？系统环境是Mac吗？

**Comment by NormalLee** [comment]
环境是linux，再次从头试了一次，可以正常下断点，非常感谢
