### ISSUE TITLE
skynet默认测试工程main 无法运行

### ISSUE THREAD

**Issue by ThisisGame** [colinsusie/skynetda#4]
自带测试配置文件完美运行，但是将配置文件中的
`start = "testvscdebug"`
修改为
`start = "main"`

即：

> root = "./"
thread = 4
logger = "vscdebuglog"
logservice = "snlua"

>logpath = "."
harbor = 0
start = "main"	-- main script
bootstrap = "snlua bootstrap"	-- The service for bootstrap

>luaservice = root.."service/?.lua;"..root.."test/?.lua;"..root.."examples/?.lua;"..root.."test/?/init.lua"
lualoader = root .. "lualib/loader.lua"
lua_path = root.."lualib/?.lua;"..root.."lualib/?/init.lua"
lua_cpath = root .. "luaclib/?.so"
snax = root.."examples/?.lua;"..root.."test/?.lua"
cpath = root.."cservice/?.so"

>vscdbg_open = "$vscdbg_open"
vscdbg_bps = [=[$vscdbg_bps]=]

调试报错

> skynet debugger start!
[:00000002] LAUNCH snlua bootstrap
[:00000003] LAUNCH snlua launcher
[:00000004] LAUNCH snlua cdummy
[:00000005] LAUNCH harbor 0 4
[:00000006] LAUNCH snlua datacenterd
[:00000007] LAUNCH snlua service_mgr
[:00000008] LAUNCH snlua main
[:00000008] start debug: 	main
[:00000009] LAUNCH snlua vscdebugd
[:00000008] Server start
[:0000000a] LAUNCH snlua protoloader
[:0000000a] start debug: 	protoloader
[:0000000b] LAUNCH snlua console
[:0000000c] LAUNCH snlua debug_console 8000
[:0000000b] lua call [0 to :b : 0 msgsz = 56] error : ./lualib/skynet.lua:642: ./lualib/skynet.lua:184: ./lualib/skynet/socket.lua:311: assertion failed!
stack traceback:
	[C]: in function 'assert'
	./lualib/skynet/socket.lua:311: in function 'skynet.socket.readline'
	./service/console.lua:16: in upvalue 'f'
	./lualib/skynet.lua:114: in function <./lualib/skynet.lua:113>
stack traceback:
	[C]: in function 'assert'
	./lualib/skynet.lua:642: in function 'skynet.dispatch_message'
[:0000000c] Start debug console at 127.0.0.1:8000
[:0000000d] LAUNCH snlua simpledb
[:0000000d] start debug: 	simpledb
[:0000000e] LAUNCH snlua watchdog
[:0000000e] start debug: 	watchdog
[:0000000f] LAUNCH snlua gate
[:0000000f] start debug: 	gate
[:0000000f] Listen on 0.0.0.0:8888
[:00000008] Watchdog listen on	8888
[:00000008] KILL self
[:00000002] KILL self
skynet debugger stop!

大佬看看是不是还需要改什么东西。

测试环境：
ubuntu18.04 
skynet-debugger 1.0.0
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)

**Comment by ThisisGame** [comment]
最后定位到socket connect失败
`local function connect(id, func)
	skynet.error("connect id:",id," func:",func)
	local newbuffer
	if func == nil then
		newbuffer = driver.buffer()
	end

	skynet.error("connect newbuffer:",newbuffer)

	local s = {
		id = id,
		buffer = newbuffer,
		connected = false,
		connecting = true,
		read_required = false,
		co = false,
		callback = func,
		protocol = "TCP",
	}
	assert(not socket_pool[id], "socket is not closed")
	socket_pool[id] = s
	suspend(s)

	local err = s.connecting
	s.connecting = nil
	if s.connected then
		skynet.error("connect success")
		return id
	else
		skynet.error("connect failed,err:",err)
		socket_pool[id] = nil
		return nil, err
	end
end`

返回错误

> connect failed,err:	reach skynet socket number limit

**Comment by ThisisGame** [comment]
> -- if not skynet.getenv "daemon" then
	-- 	local console = skynet.newservice("console")
	-- end

是这个console服务的问题，注释掉就可以。

**Comment by colinsusie** [comment]
好的谢谢，最近忙于其他事情，没太多时间看。如果没问题就好了。

**Comment by ThisisGame** [comment]
close
