### ISSUE TITLE
win10  wsl Ubuntu 20.04.1 LTS  compile error

### ISSUE THREAD

**Issue by yockguy** [colinsusie/skynetda#8]
make all PLAT=linux
make[1]: Entering directory '/mnt/d/code/gitee/skynetda'
make -C 3rd/lua linux
make[2]: Entering directory '/mnt/d/code/gitee/skynetda/3rd/lua'
cd src && make linux
make[3]: Entering directory '/mnt/d/code/gitee/skynetda/3rd/lua/src'
make a SYSCFLAGS="-DLUA_USE_LINUX" SYSLIBS="-Wl,-E -ldl -lreadline"
make[4]: Entering directory '/mnt/d/code/gitee/skynetda/3rd/lua/src'
make[4]: Nothing to be done for 'a'.
make[4]: Leaving directory '/mnt/d/code/gitee/skynetda/3rd/lua/src'
make[3]: Leaving directory '/mnt/d/code/gitee/skynetda/3rd/lua/src'
make[2]: Leaving directory '/mnt/d/code/gitee/skynetda/3rd/lua'
make -C 3rd/lua-cjson install PLAT=linux
make[2]: Entering directory '/mnt/d/code/gitee/skynetda/3rd/lua-cjson'
gcc -o cjson.so  -shared lua_cjson.o strbuf.o fpconv.o
mkdir -p ./../../vscext/bin/linux
mv cjson.so ./../../vscext/bin/linux
chmod 755 ./../../vscext/bin/linux/cjson.so
make[2]: Leaving directory '/mnt/d/code/gitee/skynetda/3rd/lua-cjson'
gcc -std=gnu99 -O2 -Wall -Wl,-E -I3rd/lua/src  -o vscext/bin/linux/skynetda src/main.c -ldl -lm -llua -L3rd/lua/src
src/main.c: In function ‘change_workdir’:
src/main.c:67:9: warning: ignoring return value of ‘chdir’, declared with attribute warn_unused_result [-Wunused-result]
   67 |         chdir(wdir);
      |         ^~~~~~~~~~~
src/main.c: In function ‘run_skynet’:
src/main.c:103:5: warning: ignoring return value of ‘chdir’, declared with attribute warn_unused_result [-Wunused-result]
  103 |     chdir(path);
      |     ^~~~~~~~~~~
/usr/bin/ld: 3rd/lua/src/liblua.a(lobject.o): in function `numarith.isra.0':
lobject.c:(.text+0x1fb): undefined reference to `fmod'
/usr/bin/ld: lobject.c:(.text+0x221): undefined reference to `pow'
/usr/bin/ld: 3rd/lua/src/liblua.a(lvm.o): in function `luaV_execute':
lvm.c:(.text+0x2145): undefined reference to `pow'
/usr/bin/ld: lvm.c:(.text+0x24e0): undefined reference to `fmod'
/usr/bin/ld: 3rd/lua/src/liblua.a(lmathlib.o): in function `math_log10':
lmathlib.c:(.text+0xa3): undefined reference to `log10'
/usr/bin/ld: 3rd/lua/src/liblua.a(lmathlib.o): in function `math_pow':
lmathlib.c:(.text+0x1b8): undefined reference to `pow'
/usr/bin/ld: 3rd/lua/src/liblua.a(lmathlib.o): in function `math_tanh':
lmathlib.c:(.text+0x1e3): undefined reference to `tanh'
/usr/bin/ld: 3rd/lua/src/liblua.a(lmathlib.o): in function `math_sinh':
lmathlib.c:(.text+0x213): undefined reference to `sinh'
/usr/bin/ld: 3rd/lua/src/liblua.a(lmathlib.o): in function `math_cosh':
lmathlib.c:(.text+0x243): undefined reference to `cosh'
/usr/bin/ld: 3rd/lua/src/liblua.a(lmathlib.o): in function `math_tan':
lmathlib.c:(.text+0x273): undefined reference to `tan'
/usr/bin/ld: 3rd/lua/src/liblua.a(lmathlib.o): in function `math_sqrt':
lmathlib.c:(.text+0x2d6): undefined reference to `sqrt'
/usr/bin/ld: 3rd/lua/src/liblua.a(lmathlib.o): in function `math_sin':
lmathlib.c:(.text+0x303): undefined reference to `sin'
/usr/bin/ld: 3rd/lua/src/liblua.a(lmathlib.o): in function `math_log':
lmathlib.c:(.text+0x649): undefined reference to `log10'
/usr/bin/ld: lmathlib.c:(.text+0x656): undefined reference to `log'
/usr/bin/ld: lmathlib.c:(.text+0x678): undefined reference to `log2'
/usr/bin/ld: lmathlib.c:(.text+0x68c): undefined reference to `log'
/usr/bin/ld: lmathlib.c:(.text+0x6a0): undefined reference to `log'
/usr/bin/ld: 3rd/lua/src/liblua.a(lmathlib.o): in function `math_exp':
lmathlib.c:(.text+0x723): undefined reference to `exp'
/usr/bin/ld: 3rd/lua/src/liblua.a(lmathlib.o): in function `math_cos':
lmathlib.c:(.text+0x753): undefined reference to `cos'
/usr/bin/ld: 3rd/lua/src/liblua.a(lmathlib.o): in function `math_atan':
lmathlib.c:(.text+0x7b0): undefined reference to `atan2'
/usr/bin/ld: 3rd/lua/src/liblua.a(lmathlib.o): in function `math_asin':
lmathlib.c:(.text+0x7e3): undefined reference to `asin'
/usr/bin/ld: 3rd/lua/src/liblua.a(lmathlib.o): in function `math_acos':
lmathlib.c:(.text+0x813): undefined reference to `acos'
/usr/bin/ld: 3rd/lua/src/liblua.a(lmathlib.o): in function `math_fmod':
lmathlib.c:(.text+0xca3): undefined reference to `fmod'
/usr/bin/ld: 3rd/lua/src/liblua.a(loadlib.o): in function `lookforfunc':
loadlib.c:(.text+0x565): undefined reference to `dlsym'
/usr/bin/ld: loadlib.c:(.text+0x5c6): undefined reference to `dlopen'
/usr/bin/ld: loadlib.c:(.text+0x649): undefined reference to `dlerror'
/usr/bin/ld: loadlib.c:(.text+0x671): undefined reference to `dlerror'
/usr/bin/ld: 3rd/lua/src/liblua.a(loadlib.o): in function `gctm':
loadlib.c:(.text+0x831): undefined reference to `dlclose'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:38: vscext/bin/linux/skynetda] Error 1
make[1]: Leaving directory '/mnt/d/code/gitee/skynetda'
make: *** [Makefile:11: linux] Error 2

**Comment by colinsusie** [comment]
Fix
