### ISSUE TITLE
服务器目录名必须是 skynet 呢？

### ISSUE THREAD

**Issue by slightun** [colinsusie/skynetda#9]
launch.json文件 的 "program": "/home/colin/skynet"
如果修改 "/home/colin/skynet" skynet 文件夹名字，会启动失败。

**Comment by colinsusie** [comment]
麻烦更新一下：https://github.com/colinsusie/skynet
已经修正了，不需要重新编译，再试试看行不行。

**Comment by slightun** [comment]
谢谢回复。上面修改不行，如果内层文件夹名字是 service 就没法调试了。
我这么修改的：
![image](https://user-images.githubusercontent.com/10279336/108817626-26007900-75f3-11eb-8982-5a841a3f2a91.png)

**Comment by slightun** [comment]
感谢回复。 上面修改不行，如果内层文件夹名是 service 就没法调试服务了。

我这么修改的：
![image](https://user-images.githubusercontent.com/10279336/108817954-a030fd80-75f3-11eb-8b3b-704a48e7bff5.png)

**Comment by colinsusie** [comment]
好的，我代码已经改过来了。

**Comment by slightun** [comment]
好勒，感谢
